export const REAGISTER_REQUREST = "REAGISTER_REQUREST";
export const REAGISTER_SUCCESS = "REAGISTER_SUCCESS";
export const REAGISTER_FAILED = "REAGISTER_FAILED";

export const LOGIN_USER_REQUREST = "LOGIN_USER_REQUREST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
