export const REAGISTER_REQUREST = "REAGISTER_REQUREST";
export const REAGISTER_SUCCESS = "REAGISTER_SUCCESS";
export const REAGISTER_FAILED = "REAGISTER_FAILED";

export const LOGIN_USER_REQUREST = "LOGIN_USER_REQUREST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const TOKEN_USER_REQUREST = "TOKEN_USER_REQUREST";
export const TOKEN_USER_SUCCESS = "TOKEN_USER_SUCCESS";
export const TOKEN_USER_FAILED = "TOKEN_USER_FAILED";

export const USER_LOGOUT = "USER_LOGOUT";

export const PROFILE_UPDATE_SAUCCESS = "PROFILE_UPDATE_SAUCCESS";
